### ISSUE TITLE
missing packet dependency ?

### ISSUE THREAD

**Issue by quasart-** [FrancescoCeruti/linux-show-player#119]
I installed linux-show-player on my lubuntu 18.4 :  `apt-get install linux-show-player`

But I get an error at startup :

```
(python3:25186): dbind-WARNING **: 10:20:55.979: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
QApplication: invalid style override passed, ignoring it.
Traceback (most recent call last):
  File "/usr/bin/linux-show-player", line 5, in <module>
    main()
  File "/usr/lib/python3/dist-packages/lisp/main.py", line 115, in main
    modules.load_modules()
  File "/usr/lib/python3/dist-packages/lisp/modules/__init__.py", line 29, in load_modules
    for name, module in load_classes(__package__, os.path.dirname(__file__)):
  File "/usr/lib/python3/dist-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/usr/lib/python3/dist-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/usr/lib/python3/dist-packages/lisp/modules/media_info/__init__.py", line 1, in <module>
    from .media_info import MediaInfo
  File "/usr/lib/python3/dist-packages/lisp/modules/media_info/media_info.py", line 28, in <module>
    from lisp.modules.gst_backend.gst_utils import gst_uri_metadata, \
  File "/usr/lib/python3/dist-packages/lisp/modules/gst_backend/__init__.py", line 4, in <module>
    from .gst_backend import GstBackend
  File "/usr/lib/python3/dist-packages/lisp/modules/gst_backend/gst_backend.py", line 25, in <module>
    from lisp.modules.gst_backend.gst_utils import gst_parse_tag_list
  File "/usr/lib/python3/dist-packages/lisp/modules/gst_backend/gst_utils.py", line 23, in <module>
    from lisp.modules.gst_backend.gi_repository import Gst, GstPbutils
  File "/usr/lib/python3/dist-packages/lisp/modules/gst_backend/gi_repository.py", line 10, in <module>
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

```

It was fixed by installing `python-gst-1.0` but I guess it should have been installed automatically and there is a missing dependency in packet configuration.

**Comment by FrancescoCeruti** [comment]
Hi, I've looked the debian/ubuntu packages, from their repository, and they're missing all the GStreamer dependencies ... you should report the bug to them (Ubuntu or Debian).

In [this](https://github.com/FrancescoCeruti/linux-show-player/wiki/Install) page of wiki you can find some info on the packages you need

**Comment by quasart-** [comment]
Thank you, I'll contact them
