### ISSUE TITLE
List Layout does'nt appear in layout selection

### ISSUE THREAD

**Issue by ghassenghouibi** [FrancescoCeruti/linux-show-player#174]
I can't select the list layout option.
I tried to run it with --log debug option and still having the same problem.
![Screenshot from 2019-05-08 14-59-14](https://user-images.githubusercontent.com/23346308/57381649-9d111700-71ab-11e9-8479-e7a6e5e33af0.png)

**Comment by ghassenghouibi** [comment]
2019-05-08 16:17:08.231	root	INFO	Using "en_US" locale -> ['en-US']
2019-05-08 16:17:08.231	lisp.ui.ui_utils	DEBUG	No translation for "qtbase" in /home/hope/.local/lib/python3.6/site-packages/PyQt5/Qt/translations
2019-05-08 16:17:08.231	lisp.ui.ui_utils	DEBUG	Installed translation for "base" from /home/hope/Documents/Informatique/Python/linux-show-player/lisp/i18n/qm
2019-05-08 16:17:08.232	root	INFO	Using "Dark" theme
2019-05-08 16:17:08.232	root	INFO	Using "Numix" icon theme
2019-05-08 16:17:08.320	lisp.ui.ui_utils	DEBUG	No translation for "presets" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/presets/i18n
2019-05-08 16:17:08.385	lisp.ui.ui_utils	DEBUG	No translation for "media_info" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/media_info/i18n
2019-05-08 16:17:08.397	lisp.ui.ui_utils	DEBUG	No translation for "midi" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/midi/i18n
2019-05-08 16:17:08.399	lisp.ui.ui_utils	DEBUG	No translation for "rename_cues" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/rename_cues/i18n
2019-05-08 16:17:08.400	lisp.core.loading	WARNING	Cannot load python module: "osc"
Traceback (most recent call last):
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 66, in load_modules
    yield mod_name, import_module(mod_path)
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 167, in import_module
    return __import__(module_path, globals(), locals(), ["*"])
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/__init__.py", line 1, in <module>
    from .osc import Osc
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/osc.py", line 22, in <module>
    from lisp.plugins.osc.osc_cue import OscCue
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/osc_cue.py", line 43, in <module>
    from lisp.plugins.osc.osc_server import OscMessageType
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/osc_server.py", line 22, in <module>
    from liblo import ServerThread, ServerError
ModuleNotFoundError: No module named 'liblo'
2019-05-08 16:17:08.404	lisp.ui.ui_utils	DEBUG	No translation for "triggers" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/triggers/i18n
2019-05-08 16:17:08.404	lisp.ui.ui_utils	DEBUG	No translation for "gst_backend" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/gst_backend/i18n
2019-05-08 16:17:08.409	lisp.ui.ui_utils	DEBUG	No translation for "timecode" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/timecode/i18n
2019-05-08 16:17:08.425	lisp.ui.ui_utils	DEBUG	No translation for "cart_layout" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/cart_layout/i18n
2019-05-08 16:17:08.428	lisp.ui.ui_utils	DEBUG	No translation for "action_cues" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/action_cues/i18n
2019-05-08 16:17:08.430	lisp.core.loading	WARNING	Cannot load python module: "network"
Traceback (most recent call last):
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 66, in load_modules
    yield mod_name, import_module(mod_path)
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 167, in import_module
    return __import__(module_path, globals(), locals(), ["*"])
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/network/__init__.py", line 1, in <module>
    from .network import Network
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/network/network.py", line 18, in <module>
    import falcon
ModuleNotFoundError: No module named 'falcon'
2019-05-08 16:17:08.433	lisp.ui.ui_utils	DEBUG	No translation for "controller" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/controller/i18n
2019-05-08 16:17:08.435	lisp.core.loading	WARNING	Cannot load python module: "list_layout"
Traceback (most recent call last):
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 66, in load_modules
    yield mod_name, import_module(mod_path)
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 167, in import_module
    return __import__(module_path, globals(), locals(), ["*"])
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/list_layout/__init__.py", line 3, in <module>
    from lisp.plugins.list_layout.layout import ListLayout as _ListLayout
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/list_layout/layout.py", line 34, in <module>
    from lisp.plugins.list_layout.list_view import CueListView
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/list_layout/list_view.py", line 31, in <module>
    from lisp.plugins.list_layout.list_widgets import (
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/list_layout/list_widgets.py", line 28, in <module>
    from pysnooper import pysnooper
ModuleNotFoundError: No module named 'pysnooper'
2019-05-08 16:17:08.582	lisp.core.loading	WARNING	Cannot load python module: "synchronizer"
Traceback (most recent call last):
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 66, in load_modules
    yield mod_name, import_module(mod_path)
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 167, in import_module
    return __import__(module_path, globals(), locals(), ["*"])
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/synchronizer/__init__.py", line 1, in <module>
    from .synchronizer import Synchronizer
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/synchronizer/synchronizer.py", line 27, in <module>
    from lisp.plugins.network.discovery_dialogs import HostManagementDialog
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/network/__init__.py", line 1, in <module>
    from .network import Network
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/network/network.py", line 18, in <module>
    import falcon
ModuleNotFoundError: No module named 'falcon'
2019-05-08 16:17:08.610	lisp.ui.ui_utils	DEBUG	No translation for "replay_gain" in /home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/replay_gain/i18n
2019-05-08 16:17:08.612	lisp.plugins	INFO	Plugin loaded: "Presets"
2019-05-08 16:17:08.613	lisp.ui.mainwindow	DEBUG	Registered cue menu: "MIDI Cue"
2019-05-08 16:17:08.627	lisp.plugins	INFO	Plugin loaded: "Midi"
2019-05-08 16:17:08.627	lisp.plugins	INFO	Plugin loaded: "RenameCues"
2019-05-08 16:17:08.629	lisp.plugins	INFO	Plugin loaded: "Triggers"
2019-05-08 16:17:08.653	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Audio cue (from file)"
2019-05-08 16:17:08.695	lisp.plugins	INFO	Plugin loaded: "GstBackend"
2019-05-08 16:17:08.697	lisp.core.loading	WARNING	Cannot load python module: "artnet"
Traceback (most recent call last):
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 66, in load_modules
    yield mod_name, import_module(mod_path)
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 167, in import_module
    return __import__(module_path, globals(), locals(), ["*"])
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/timecode/protocols/artnet.py", line 21, in <module>
    from ola.OlaClient import OlaClient, OLADNotRunningException
ModuleNotFoundError: No module named 'ola'
2019-05-08 16:17:08.699	lisp.plugins	INFO	Plugin loaded: "Timecode"
2019-05-08 16:17:08.699	lisp.plugins	INFO	Plugin loaded: "CartLayout"
2019-05-08 16:17:08.700	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Volume Control"
2019-05-08 16:17:08.702	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Collection Cue"
2019-05-08 16:17:08.703	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Stop-All"
2019-05-08 16:17:08.704	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Command Cue"
2019-05-08 16:17:08.705	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Index Action"
2019-05-08 16:17:08.706	lisp.ui.mainwindow	DEBUG	Registered cue menu: "Seek Cue"
2019-05-08 16:17:08.706	lisp.plugins	INFO	Plugin loaded: "ActionCues"
2019-05-08 16:17:08.707	lisp.plugins	INFO	Plugin loaded: "ReplayGain"
2019-05-08 16:17:08.707	lisp.plugins	INFO	Plugin loaded: "MediaInfo"
2019-05-08 16:17:08.713	lisp.core.loading	WARNING	Cannot load python module: "osc"
Traceback (most recent call last):
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 66, in load_modules
    yield mod_name, import_module(mod_path)
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/core/loading.py", line 167, in import_module
    return __import__(module_path, globals(), locals(), ["*"])
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/controller/protocols/osc.py", line 41, in <module>
    from lisp.plugins.osc.osc_delegate import OscArgumentDelegate
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/__init__.py", line 1, in <module>
    from .osc import Osc
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/osc.py", line 22, in <module>
    from lisp.plugins.osc.osc_cue import OscCue
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/osc_cue.py", line 43, in <module>
    from lisp.plugins.osc.osc_server import OscMessageType
  File "/home/hope/Documents/Informatique/Python/linux-show-player/lisp/plugins/osc/osc_server.py", line 22, in <module>
    from liblo import ServerThread, ServerError
ModuleNotFoundError: No module named 'liblo'
2019-05-08 16:17:08.716	lisp.plugins	INFO	Plugin loaded: "Controller"

**Comment by FrancescoCeruti** [comment]
Ah, my fault, I've left an unwanted import there, I'll fix that, thanks :)

**Comment by FrancescoCeruti** [comment]
Can you write here the output you get in the terminal when using the `--log debug` option? Thanks :)
