### ISSUE TITLE
Trying to set the keys for every action

### ISSUE THREAD

**Issue by alfonsoler** [FrancescoCeruti/linux-show-player#197]
I bought Airturn BT-200 S-2, which has several options for 2 buttons. I use option 5, which triggers SPACE and ENTER. Using keyboard has the exact same effect  (none right now).

#### Expected Behavior
SPACE makes next cue happen.
ENTER Stops actual cue. Fade out expected.

#### Actual Behavior
A) Until yesterday

Enter Key did not have any effect.
Space key worked but although I had "do nothing" in the cue options, as I pressed it, it just played the next cue along with the one already playing. Both sound together, no fade out of the first one, no stopping the first one,...

B) From yesterday
Nothing happens and I cannot find any place to say what key should be "go" and which should be (little)"stop". That should be editable.

#### Step to reproduce
Install, add more than one cue and try to make it happen with keyboard.

**Comment by s0600204** [comment]
Greetings!

1. What version of LiSP are you running?
2. How did you initially tell LiSP what to do when it receives `SPACE` and `ENTER` key presses?
3. Do those characters appear within other applications when they have focus?
4. Did you set a fade-out time for each cue?

**Comment by alfonsoler** [comment]
Hello! Thanks for your answer.

    What version of LiSP are you running?
0.5.1 (sudo apt install in Ubuntu). I tried the AppImage, but this will not open after asking about it being merged in my system.
    How did you initially tell LiSP what to do when it receives SPACE and ENTER key presses?
I do honestly don't know, since I cannot find that again. I am sure about having seen it somewhere, but now I cannot find that. Like Enter is start cue and Space end it.
    Do those characters appear within other applications when they have focus?
Yes. I tried more than one App. I can write in LibreOffice and use them without problems, as well as in Firefox and so on.
    Did you set a fade-out time for each cue?
In some of them yes. First one has no fade-in/out, second only a fade-out of 3 secs and third cue has both along with starting times and repetitions. This works perfectly.

**Comment by FrancescoCeruti** [comment]
Hi!

> SPACE makes next cue happen.

to change the "GO" key you should look at `File->Preferences->List Layout->Go key`.

> ENTER Stops actual cue. Fade out expected.

depends on what you mean with _actual_, if you refer to the highlighted one, then "GO" will perform a different action depending on the current state of the cue (play/pause/stop) and the cue configuration (Start/Stop action in `Cue->Behaviors`). Otherwise, depending on your needs, you could use some other methods:

1. a `Stop All` cue triggered by a key (in 0.5.1 you cannot use ENTER), this will stop any running cue
2. a trigger on the cues where you need to stop the previous one

> Space key worked but although I had "do nothing" in the cue options as I pressed it, it just played the next cue

:thinking: you probably changed the `Next Action` option, right? the naming is a bit confusing, but it refers to what should happen after the cue post-wait.

**Comment by alfonsoler** [comment]
I tried it again and the program doesn't do a thing. Not with the keyboard nor with the pedal. I press enter or space and nothing happens.
I tried to change the GO button shortcut and that does not work at all. I have to click. I am using List Layout.

Next Action is "Do Nothing".

**Comment by FrancescoCeruti** [comment]
> I press enter or space and nothing happens. 
> I tried to change the GO button shortcut and that does not work at all. I have to click. I am using List Layout.

I forgot to mention, you need to restart LiSP for that setting to be effected. Have you tried?

If the problem persists, try to run `linux-show-player --log debug` in the console and use the GO key, then post here the output. The configuration file might be useful too, you can get the content via `cat $HOME/.linux_show_player/config.cfg`.

**Comment by alfonsoler** [comment]
> inux-show-player --log debug
12:41:36.469 INFO:: Using es_ES locale
12:41:36.522 DEBUG:: MODULES: Loaded "MediaCueMenus"
12:41:36.595 DEBUG:: MODULES: Loaded "GstBackend"
12:41:36.600 DEBUG:: MODULES: Loaded "Presets"
12:41:36.601 DEBUG:: MODULES: Loaded "UriChanger"
12:41:36.603 DEBUG:: MODULES: Loaded "ReplayGain"
12:41:36.626 DEBUG:: MODULES: Loaded "MediaInfo"
12:41:36.642 INFO:: REMOTE: Session started at ('0.0.0.0', 8070)
12:41:36.642 DEBUG:: MODULES: Loaded "Remote"
12:41:36.652 DEBUG:: MODULES: Loaded "Midi"
12:41:36.653 DEBUG:: ACTION-CUES: Loaded "MidiCue"
12:41:36.655 DEBUG:: ACTION-CUES: Loaded "CommandCue"
12:41:36.661 DEBUG:: ACTION-CUES: Loaded "SeekCue"
12:41:36.662 DEBUG:: ACTION-CUES: Loaded "VolumeControl"
12:41:36.664 DEBUG:: ACTION-CUES: Loaded "CollectionCue"
12:41:36.664 DEBUG:: ACTION-CUES: Loaded "StopAll"
12:41:36.665 DEBUG:: ACTION-CUES: Loaded "IndexActionCue"
12:41:36.665 DEBUG:: MODULES: Loaded "ActionCues"
12:41:36.671 DEBUG:: PLUGINS: Loaded "Controller"
12:41:36.671 WARNING:: Cannot load module: timecode
12:41:36.672 DEBUG:: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lisp/plugins/timecode/__init__.py", line 22, in <module>
    import ola
ModuleNotFoundError: No module named 'ola'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/usr/lib/python3/dist-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/usr/lib/python3/dist-packages/lisp/plugins/timecode/__init__.py", line 25, in <module>
    raise ImportError('OLA module not found, plugin not loaded.')
ImportError: OLA module not found, plugin not loaded.

12:41:36.673 DEBUG:: PLUGINS: Loaded "Triggers"
12:41:36.674 DEBUG:: PLUGINS: Loaded "Synchronizer"
12:41:49.946 DEBUG:: PLUGINS: Initialized "Controller"
12:41:49.946 DEBUG:: PLUGINS: Initialized "Triggers"
12:41:49.946 DEBUG:: PLUGINS: Initialized "Synchronizer"
12:41:49.967 INFO:: Last action: AddItemAction
12:41:49.974 INFO:: Last action: AddItemAction
12:41:49.980 INFO:: Last action: AddItemAction
12:43:20.699 DEBUG:: MODULES: Terminated "MediaCueMenus"
12:43:20.699 DEBUG:: MODULES: Terminated "GstBackend"
12:43:20.699 DEBUG:: MODULES: Terminated "Presets"
12:43:20.700 DEBUG:: MODULES: Terminated "UriChanger"
12:43:20.700 DEBUG:: MODULES: Terminated "ReplayGain"
12:43:20.700 DEBUG:: MODULES: Terminated "MediaInfo"
12:43:20.766 DEBUG:: MODULES: Terminated "Remote"
12:43:20.767 DEBUG:: MODULES: Terminated "Midi"
12:43:20.767 DEBUG:: MODULES: Terminated "ActionCues"
12:43:20.767 DEBUG:: PLUGINS: Reset "Controller"
12:43:20.768 INFO:: REMOTE: Session ended
12:43:20.768 DEBUG:: PLUGINS: Reset "Triggers"
12:43:20.769 DEBUG:: PLUGINS: Reset "Synchronizer"

**Comment by alfonsoler** [comment]
[Version]
number = 20

[Cue]
fadeactionduration = 3.0
fadeactiontype = Linear
interruptfade = 3.0
interruptfadetype = Linear

[Theme]
theme = Dark
icons = numix

[Backend]
default = gst

[Gst]
pipeline = Volume, Equalizer10, DbMeter, AutoSink

[Layout]
default = NoDefault

[MIDI]
inputdevice = SysDefault
outputdevice = SysDefault
backend = mido.backends.rtmidi

[Remote]
bindip = 0.0.0.0
bindport = 8070
discoverport = 50000
discovermagic = L1SPR3m0t3

[Actions]
maxstacksize = 0

[CartLayout]
gridcolumns = 7
gridrows = 4
showseek = False
showdbmeters = False
showaccurate = False
showvolume = False
countdown = True
autoaddpage = True

[ListLayout]
showdbmeters = True
showseek = True
showaccurate = False
showplaying = True
autocontinue = True
endlist = Stop
gokey = Backspace
stopcuefade = True
pausecuefade = True
resumecuefade = True
interruptcuefade = True
stopallfade = False
pauseallfade = False
resumeallfade = False
interruptallfade = True

[DbMeter]
dbmax = 0
dbmin = -60
dbclip = 0

[Timecode]
enabled = True
format = FILM
hres = True

**Comment by FrancescoCeruti** [comment]
I don't see any related error, but the GO key in the configuration is set to `Backspace`, not `Space`.

Maybe i misunderstood this `I tried to change the GO button shortcut and that does not work at all.`, did you meant you couldn't  change the setting value?

**Comment by alfonsoler** [comment]
I was able to change it, although it was a bit strange. Now Go is set to Enter again.
I added a blank audio that I made with Audacity and added to it a trigger:
Trigger: Started
Cue 1|02...
Action: Default (There was no way of choosing what action should be triggered or so)
This made the trick. Still would be nice to have control over the buttons and be able to freely choose the key that triggers them, so we can take advantage of our hardware.
I would be amazing to:
Enter does GO
Space does Stop current cue and preselect the next one.

I am gonna check out if I can send you some coffee money!
