### ISSUE TITLE
Ported from Google: Issue 13: Modules fail to load

### ISSUE THREAD

**Issue by Mr-Si** [FrancescoCeruti/linux-show-player#2]
Hi Francesco,

Just for completeness, I am logging my issue here as you prefer.
This is the chain so far:

My original Message:
What steps will reproduce the problem?
1.Open the program from scratch
2.module "midi" loading failed, click ok
3.module "gst" loading failed, click ok
4.load cart mode or list mode
5.module "controller" loading failed, click ok
6.no option in the edit menu to add media

What version of the product are you using? On what operating system?
Tried version 0.2.2 and the latest version 0.3.1 from Github. OS is Ubuntu Studio 14.04 LTS

Please provide any additional information below.
am running it on a Dell Vostro 1000 laptop.

Your Reply:
Hi,
is your OS 64bit? If so try to launch it from the command line with "--log debug" option and post the result.

If you are using a 32bit system, as soon as I can a 32bit package will be released.

P.S.
Next time use the github issues manager, http://google-opensource.blogspot.it/2015/03/farewell-to-google-code.html ;)

My Response:
Hi Sorry, I wasn't quite sure which place to post the bug and then I saw this bit on Google, so if I will post my reply here for completeness, but I will also open the bug on github with all the included bits from here, so that it's open in the newest place.

my OS is 64 bit, yes.

The output of the debug log is as follows:

barrett@BarrettLaptop1:~$ linux-show-player --log debug
Configuration is up to date
ERROR:: MODULES: Failed "midi" loading
DEBUG:: MODULES: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/__init__.py", line 23, in init_modules
    mod = import_module('lisp.modules.' + pkg)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/__init__.py", line 3, in <module>
    from lisp.modules.midi.midi import InputMidiHandler
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/midi.py", line 8, in <module>
    import mido
ImportError: No module named 'mido'

INFO:: REMOTE: Session started at ('127.0.1.1', 8070)
DEBUG:: MODULES: Loaded "remote"
DEBUG:: ACTION-CUES: Loaded "GroupsAction"
DEBUG:: ACTION-CUES: Loaded "SeekAction"
DEBUG:: ACTION-CUES: Loaded "StopAll"
DEBUG:: MODULES: Loaded "action_cues"
ERROR:: MODULES: Failed "gst" loading
DEBUG:: MODULES: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/__init__.py", line 24, in init_modules
    mod.initialize()
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/gst/__init__.py", line 32, in initialize
    elements.load()
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/gst/elements/__init__.py", line 13, in load
    for _, element in load_classes(os.path.dirname(__file__)):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/utils/dyamic_loader.py", line 42, in load
    module = loader.find_module(mod_name).load_module(mod_name)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1591, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/gst/elements/jack_sink.py", line 7, in <module>
    import jack
  File "/usr/local/lib/python3.4/dist-packages/JACK_Client-0.3.0-py3.4.egg/jack.py", line 30, in <module>
    from cffi import FFI as _FFI
ImportError: No module named 'cffi'

ERROR:: PLUGINS: Failed "controller" load
DEBUG:: PLUGINS: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/plugins/__init__.py", line 25, in init_plugins
    module = import_module('lisp.plugins.' + pkg + '.' + pkg)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/plugins/controller/controller.py", line 13, in <module>
    from lisp.modules.midi.midi import InputMidiHandler
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/__init__.py", line 3, in <module>
    from lisp.modules.midi.midi import InputMidiHandler
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/midi.py", line 8, in <module>
    import mido
ImportError: No module named 'mido'

DEBUG:: PLUGINS: Loaded "replay_gain"
DEBUG:: PLUGINS: Loaded "uri_changer"
DEBUG:: PLUGINS: Loaded "triggers"
DEBUG:: PLUGINS: Loaded "media_info"
DEBUG:: PLUGINS: Loaded "synchronizer"

Thanks,
Si

**Comment by FrancescoCeruti** [comment]
mmmh, looks like a missing pair of dependency, have you used the ".deb" package?

**Comment by Mr-Si** [comment]
I did for version 0.2.3 but the 0.3.1 I didn't. I thought I'd downloaded all the dependencies, but if there's a deb for the newer version, I'll try that...

**Comment by FrancescoCeruti** [comment]
My bad, i need to update the instruction on the readme file, you can find it in the releases section :)

**Comment by Mr-Si** [comment]
Hi,
Thanks for that. 
I downloaded it but it gave a warning of a bad quality package file (not sure why, coding's not my main strength)

I now have the option to load audio files now in the edit menu, so that's good, but am still getting the midi and mido module failures:

Here's my latest output:


barrett@BarrettLaptop1:~$ linux-show-player --log debug
Configuration is up to date
ERROR:: MODULES: Failed "midi" loading
DEBUG:: MODULES: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mido/backends/backend.py", line 25, in _import_module
    return importlib.import_module(module, package)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/mido/backends/rtmidi.py", line 9, in <module>
    import rtmidi
  File "/usr/lib/python3.4/dist-packages/rtmidi/__init__.py", line 4, in <module>
    from ._rtmidi import *
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/python3.4/dist-packages/rtmidi/_rtmidi.cpython-34m.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/midi.py", line 33, in start
    self.__backend = mido.Backend(self.__backend_name, load=True)
  File "/usr/local/lib/python3.4/dist-packages/mido/backends/backend.py", line 53, in __init__
    self.load()
  File "/usr/local/lib/python3.4/dist-packages/mido/backends/backend.py", line 79, in load
    self._module = _import_module(self.name)
  File "/usr/local/lib/python3.4/dist-packages/mido/backends/backend.py", line 27, in _import_module
    raise ImportError('No module named {}'.format(name))
ImportError: No module named mido.backends.rtmidi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/__init__.py", line 24, in init_modules
    mod.initialize()
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/__init__.py", line 16, in initialize
    InputMidiHandler().start()
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/midi/midi.py", line 37, in start
    self.__backend_name)
RuntimeError: Backend loading failed: mido.backends.rtmidi

INFO:: REMOTE: Session started at ('127.0.1.1', 8070)
DEBUG:: MODULES: Loaded "remote"
DEBUG:: ACTION-CUES: Loaded "GroupsAction"
DEBUG:: ACTION-CUES: Loaded "SeekAction"
DEBUG:: ACTION-CUES: Loaded "StopAll"
DEBUG:: MODULES: Loaded "action_cues"
DEBUG:: MODULES: Loaded "gst"
ERROR:: MODULES: Failed "mido" loading
DEBUG:: MODULES: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linux_show_player-0.3.1-py3.4.egg/lisp/modules/__init__.py", line 24, in init_modules
    mod.initialize()
AttributeError: 'module' object has no attribute 'initialize'

DEBUG:: PLUGINS: Loaded "controller"
DEBUG:: PLUGINS: Loaded "replay_gain"
DEBUG:: PLUGINS: Loaded "uri_changer"
DEBUG:: PLUGINS: Loaded "triggers"
DEBUG:: PLUGINS: Loaded "media_info"
DEBUG:: PLUGINS: Loaded "synchronizer"

**Comment by Mr-Si** [comment]
I think that's a problem with my machine though, from me playing around and I need to reinstall this distro anyway, so I shall try again by going direct to the releases area and downloading the latest deb.

Thanks for your help!

**Comment by FrancescoCeruti** [comment]
The problem is that the package is builded on Ubuntu 14.10 and the libstdc++6 version is newer, you can try to install "rtmidi" over the one provided with my package so can be recompiled (<code>pip3 install python-rtmidi</code>).

**Comment by Mr-Si** [comment]
Hi Francesco,

Considering that you built it on 14.10, would it be wise to use specifically that release or can I safely use the latest release?

Many thanks
Simon

On 19 July 2015 14:38:15 BST, Francesco Ceruti <notifications@github.com> wrote:
>The problem is that the package is builded on Ubuntu 14.10 and the
>libstdc++6 version is newer, you can try to install "rtmidi" over the
>one provided with my package so can be recompiled (<code>pip3 install
>python-rtmidi</code>).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/FrancescoCeruti/linux-show-player/issues/2#issuecomment-122661532

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by FrancescoCeruti** [comment]
Hi,
I think that you can safely use the last release, but not sure at 100%, unfortunately sometimes they do strange stuff with their packages ...

**Comment by Mr-Si** [comment]
Excellent, 

Thanks for your quick reply. I initially chose 14.04 as it was the latest LTS release and thought I would play safe but I shall say goodbye to that.

Cheers,
Si

On 20 July 2015 19:16:21 BST, Francesco Ceruti <notifications@github.com> wrote:
>Hi,
>I think that you can safely use the last release, but not sure at 100%,
>unfortunately sometimes they do strange stuff with their packages ...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/FrancescoCeruti/linux-show-player/issues/2#issuecomment-122972370

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
