### ISSUE TITLE
Program crashes when media playback slider is clicked

### ISSUE THREAD

**Issue by InTheMorning** [FrancescoCeruti/linux-show-player#242]
When trying to jog through the media cue's progress slider, the program immediately crashes.

1. Add a media cue
2. Start cue playback
3. Click on the playback progress slider widget

Linux Show Player versions:
- 0.5.3
- 0.5.3-r280-d19da9ce

**OS Version**
 - ArchLinux

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lisp/ui/widgets/qclickslider.py", line 29, in mousePressEvent
    cr = self._control_rect()
  File "/usr/lib/python3.10/site-packages/lisp/ui/widgets/qclickslider.py", line 56, in _control_rect
    return self.style().subControlRect(QStyle.CC_Slider, opt,
TypeError: subControlRect(self, QStyle.ComplexControl, QStyleOptionComplex, QStyle.SubControl, QWidget): not enough arguments
Fatal Python error: Aborted

Thread 0x00007f7a67fff640 (most recent call first):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/lib/python3.10/threading.py", line 946 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Thread 0x00007f7a77311640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/lisp/modules/remote/discovery.py", line 45 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Thread 0x00007f7a77b12640 (most recent call first):
  File "/usr/lib/python3.10/selectors.py", line 416 in select
  File "/usr/lib/python3.10/socketserver.py", line 232 in serve_forever
  File "/usr/lib/python3.10/site-packages/lisp/modules/remote/controller.py", line 69 in start
  File "/usr/lib/python3.10/threading.py", line 946 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007f7aa9dc6740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/lisp/main.py", line 129 in main
  File "/usr/bin/linux-show-player", line 5 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, gi._gi, cairo._cairo, gi._gi_cairo (total: 6)

```

**Comment by FrancescoCeruti** [comment]
I can't reproduce the issue on ArchLinux, did you install the package from the AUR? Can you tell me the PyQt5 version you've installed (`pip list | grep PyQt5`)?

**Comment by InTheMorning** [comment]
Pyqt=5.15.6

I installed from the AUR

**Comment by FrancescoCeruti** [comment]
It seems like the PyQt you've installed has something off.

This method:
`subControlRect(self, QStyle.ComplexControl, QStyleOptionComplex, QStyle.SubControl, QWidget)`
Should be like this:
`subControlRect(self, QStyle.ComplexControl, QStyleOptionComplex, QStyle.SubControl, widget: QWidget = None)`

Try to reinstall `python-pyqt5`, from the official repository,  this is what I'm using:

```
Name            : python-pyqt5
Version         : 5.15.6-7
Description     : A set of Python bindings for the Qt5 toolkit
Architecture    : x86_64
Installed Size  : 26.28 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Mon Jan 31 08:52:31 2022
```
