### ISSUE TITLE
player will not start, throws an error in terminal.

### ISSUE THREAD

**Issue by pcowley** [FrancescoCeruti/linux-show-player#250]
Hi

I have installed the version from the repository for Ubuntu 22.04.
The software installs with no error and the menu item gets created but clicking on it causes a taskbar icon to show very briefly then vanish.
On running it from the terminal to see if there is an error, I find there is an error with traceback as shown below:

Traceback (most recent call last):
  File "/usr/bin/linux-show-player", line 3, in <module>
    from lisp.main import main
  File "/usr/lib/python3/dist-packages/lisp/main.py", line 30, in <module>
    from lisp import modules
  File "/usr/lib/python3/dist-packages/lisp/modules/__init__.py", line 23, in <module>
    from lisp.ui import elogging
  File "/usr/lib/python3/dist-packages/lisp/ui/elogging.py", line 28, in <module>
    from lisp.ui.widgets import QDetailedMessageBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/__init__.py", line 1, in <module>
    from .cueaction_combobox import CueActionComboBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/cueaction_combobox.py", line 25, in <module>
    from lisp.cues.cue import Cue, CueAction
  File "/usr/lib/python3/dist-packages/lisp/cues/cue.py", line 25, in <module>
    from lisp.core.fade_functions import FadeInType, FadeOutType
  File "/usr/lib/python3/dist-packages/lisp/core/fade_functions.py", line 32, in <module>
    from lisp.core.util import FunctionProxy
  File "/usr/lib/python3/dist-packages/lisp/core/util.py", line 22, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Linux Show Player version:**
-  0.5.2-1

**OS Version**
 - Ubuntu 22.04 LTS]

**Additional context**
I have uninstalled and reinstalled with a reboot in between but that made no difference.

I am really keen to get this going as I have been asked to help with a theatre show - they usually use QLab on a Mac but the person who created all the initial queues (due to COVID causing a delay in the productions is now working on another show).  I have been making do with a windows only piece of software, which is extremely flaky, but would love to have this work on my Linux laptop.

Cheers
Pete Cowley

**Comment by keithjnewman** [comment]
I had the same issue.  I got around it by downloading 0.5.3 and doing a manual install.  It didn't add to the menu but runs fine when started from a command prompt.

**Comment by pcowley** [comment]
Thanks Keith for that info.  I see the 5.3 version is going to be available in Ubuntu 22.10 - still a couple of months away.
Will try the applimage version and see how it goes in the meantime.

Cheers

**Comment by s0600204** [comment]
See also: #245, #238

As this is a downstream issue - and one that keeps being reported to us - a bug report has been filed on the Ubuntu bug tracker: https://bugs.launchpad.net/ubuntu/+source/linux-show-player/+bug/1987073
