### ISSUE TITLE
Backend not loaded, appimage v.0.5.2

### ISSUE THREAD

**Issue by ZephB404** [FrancescoCeruti/linux-show-player#261]
Hi,
I'm on the most recent version of POP! OS. Tried to install the software via "apt-get", had no success, LiSP would not even launch. This is what i got back in the terminal
`Traceback (most recent call last):
  File "/usr/bin/linux-show-player", line 3, in <module>
    from lisp.main import main
  File "/usr/lib/python3/dist-packages/lisp/main.py", line 30, in <module>
    from lisp import modules
  File "/usr/lib/python3/dist-packages/lisp/modules/__init__.py", line 23, in <module>
    from lisp.ui import elogging
  File "/usr/lib/python3/dist-packages/lisp/ui/elogging.py", line 28, in <module>
    from lisp.ui.widgets import QDetailedMessageBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/__init__.py", line 1, in <module>
    from .cueaction_combobox import CueActionComboBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/cueaction_combobox.py", line 25, in <module>
    from lisp.cues.cue import Cue, CueAction
  File "/usr/lib/python3/dist-packages/lisp/cues/cue.py", line 25, in <module>
    from lisp.core.fade_functions import FadeInType, FadeOutType
  File "/usr/lib/python3/dist-packages/lisp/core/fade_functions.py", line 32, in <module>
    from lisp.core.util import FunctionProxy
  File "/usr/lib/python3/dist-packages/lisp/core/util.py", line 22, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
`
So I downloaded the appimage. The application launched wonderfully! But when creating a media cue i get the error "Backend not loaded", i went into my preference tab and there is not even a Gstreamer option. How can I solve this?

**Comment by s0600204** [comment]
Hi!

The `ImportError` has been reported previously, notably in #250, and is a downstream packaging problem requiring Ubuntu (which Pop OS reuses the repositories of) to update their package of `LiSP` for Ubuntu 22.04.

The downstream bug report for this is here: https://bugs.launchpad.net/ubuntu/+source/linux-show-player/+bug/1987073

According to Wikipedia the team behind Pop OS will be skipping/have skipped having a 22.10 release; which is unfortunate as it would have pulled in the Ubuntu 22.10 repos (which contain `LiSP v0.5.3` that fixes the problem).

The appimage error has also been reported previously - in #238 - details about that can be found there.

At the moment, the solution is to install `LiSP v0.5.3` from source: https://github.com/FrancescoCeruti/linux-show-player/wiki/Install#manual-installation
