### ISSUE TITLE
Not working on PopOs

### ISSUE THREAD

**Issue by piermarco** [FrancescoCeruti/linux-show-player#279]
**Describe the bug**
Not working on PopOs

**To Reproduce**
Installed via apt and flatpak, same issue

**Expected behavior**

**Screenshots**
sudo linux-show-player
Create new configuration file: /root/.linux_show_player/config.cfg
Traceback (most recent call last):
  File "/usr/bin/linux-show-player", line 3, in <module>
    from lisp.main import main
  File "/usr/lib/python3/dist-packages/lisp/main.py", line 30, in <module>
    from lisp import modules
  File "/usr/lib/python3/dist-packages/lisp/modules/__init__.py", line 23, in <module>
    from lisp.ui import elogging
  File "/usr/lib/python3/dist-packages/lisp/ui/elogging.py", line 28, in <module>
    from lisp.ui.widgets import QDetailedMessageBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/__init__.py", line 1, in <module>
    from .cueaction_combobox import CueActionComboBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/cueaction_combobox.py", line 25, in <module>
    from lisp.cues.cue import Cue, CueAction
  File "/usr/lib/python3/dist-packages/lisp/cues/cue.py", line 25, in <module>
    from lisp.core.fade_functions import FadeInType, FadeOutType
  File "/usr/lib/python3/dist-packages/lisp/core/fade_functions.py", line 32, in <module>
    from lisp.core.util import FunctionProxy
  File "/usr/lib/python3/dist-packages/lisp/core/util.py", line 22, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Linux Show Player version:**
0.5.2-1

**OS Version**
PopOs: Linux pop-os 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by FrancescoCeruti** [comment]
See #245, same problem.

The flatpak version should not be affected by this problem. 
Did you run it the command line with `flatpak run org.linux_show_player.LinuxShowPlayer`?
