### ISSUE TITLE
Problem with Python 3.11 cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

### ISSUE THREAD

**Issue by Pete-beep** [FrancescoCeruti/linux-show-player#281]
I have a new install using 
sudo apt-get install linux-show-player

when launching 

pc:~$ linux-show-player
Traceback (most recent call last):
  File "/usr/bin/linux-show-player", line 3, in <module>
    from lisp.main import main
  File "/usr/lib/python3/dist-packages/lisp/main.py", line 30, in <module>
    from lisp import modules
  File "/usr/lib/python3/dist-packages/lisp/modules/__init__.py", line 23, in <module>
    from lisp.ui import elogging
  File "/usr/lib/python3/dist-packages/lisp/ui/elogging.py", line 28, in <module>
    from lisp.ui.widgets import QDetailedMessageBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/__init__.py", line 1, in <module>
    from .cueaction_combobox import CueActionComboBox
  File "/usr/lib/python3/dist-packages/lisp/ui/widgets/cueaction_combobox.py", line 25, in <module>
    from lisp.cues.cue import Cue, CueAction
  File "/usr/lib/python3/dist-packages/lisp/cues/cue.py", line 25, in <module>
    from lisp.core.fade_functions import FadeInType, FadeOutType
  File "/usr/lib/python3/dist-packages/lisp/core/fade_functions.py", line 32, in <module>
    from lisp.core.util import FunctionProxy
  File "/usr/lib/python3/dist-packages/lisp/core/util.py", line 22, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by FrancescoCeruti** [comment]
See #245 the version in some repositories is incompatible with python >= 3.10 (https://bugs.launchpad.net/ubuntu/+source/linux-show-player/+bug/1987073).

My suggestion is to use the flatpak version: https://github.com/FrancescoCeruti/linux-show-player/releases/tag/ci-develop
