### ISSUE TITLE
Jack playback with pipewire on arch is currently broken

### ISSUE THREAD

**Issue by radiomike** [FrancescoCeruti/linux-show-player#286]
**Describe the bug**
If jack is set as the output, cues don't  play and the below error is shown on adding cue and attempted playback

```2023-11-03 15:14:35.604	lisp.plugins.gst_backend.gst_media	ERROR	GStreamer: Resource not found.
lisp.plugins.gst_backend.gst_utils.GstError: ../gstreamer/subprojects/gst-plugins-good/ext/jack/gstjackaudiosink.c(308): jack_shutdown_cb (): /GstPipeline:pipeline0/GstJackAudioSink:sink:
Jack server shutdown```


**To Reproduce**
Steps to reproduce the behavior:
1. Add a cue

**Expected behavior**
Cues should playback

**Screenshots**
![Screenshot from 2023-11-03 15-33-14](https://github.com/FrancescoCeruti/linux-show-player/assets/11080876/ac01f65c-b4f7-46a6-87da-bb8fc659a479)
![Screenshot from 2023-11-03 15-33-06](https://github.com/FrancescoCeruti/linux-show-player/assets/11080876/b8748180-3385-41c0-af94-d768f3866c55)


**Linux Show Player version:**
- 0.6

**OS Version**
 - Arch
 - Pipewire 0.3.84 with pipewire-jack

**Additional context**
Run from git using `poetry run linux-show-player`
This was working previously, not sure if it's a pipewire or LISP update that's broken things.
[LISP debug log](https://github.com/FrancescoCeruti/linux-show-player/files/13251887/LISP.debug.log)

**Comment by FrancescoCeruti** [comment]
It's some sort of incompatibility between the gstreamer jack-client and the pipewire jack-server implementation.
Likely the same, or very similar to https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2324.

This time I can try to see if the gstreamer devs can fix the issue.

In the meantime, to avoid the issue you could try this: https://wiki.archlinux.org/title/PipeWire#Run_PipeWire_on_top_of_native_JACK

**Comment by FrancescoCeruti** [comment]
Issue for gstreamer: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3092

**Comment by bruggor10** [comment]
Hello all, 
I am glad to report that I got linux-show-player successfully working with jack support under Pipewire.
What worked for me:
- tuxedo os (based on Ubuntu 24.04)
- using `pipewire-jack` (the standard pipewire jack setup):
 ```
sudo apt install pipewire-jack
sudo cp /usr/share/doc/pipewire/examples/ld.so.conf.d/pipewire-jack-*.conf /etc/ld.so.conf.d/
sudo ldconfig
```

- manual installation of linux-show-player (https://linux-show-player-users.readthedocs.io/en/latest/installation.html#manually) which gave me no audio backend at all
- additional packages I installed: `python3-gst-1.0 python3-jack-client python3-mido`

afterwords, it worked perfectly for me when selecting the jack backend.
Hope this is helpful.

**Comment by wargreen** [comment]
Installed via Flathub, not working, with or without pw-jack.
Maybe something wrong in my configuration ?

Debian SID, pipewire installed but not with in-place jack's libs (need jack sometime). 
LiSP 0.6.5 from flathub.

My audio outputs and devices are listed perfectly in the connection editors.

Commandline `wargreen@fetide~> flatpak run org.linuxshowplayer.LinuxShowPlayer` & `pw-jack flatpak run org.linuxshowplayer.LinuxShowPlayer`, new session with the same sample : 
```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lisp/plugins/gst_backend/gst_media.py", line 245, in __init_pipeline
    self.elements.append(all_elements[element](self.__pipeline))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lisp/plugins/gst_backend/elements/jack_sink.py", line 59, in __init__
    self.jack_sink.set_property("client-name", self._client_name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_property'
2026-09-10 22:49:36.053	lisp.plugins.gst_backend.gst_media	ERROR	GStreamer: Internal data stream error.
lisp.plugins.gst_backend.gst_utils.GstError: ../gst/wavparse/gstwavparse.c(2370): gst_wavparse_loop (): /GstPipeline:pipeline0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstWavParse:wavparse0:
streaming stopped, reason not-linked (-1)
2026-09-10 22:49:36.056	lisp.core.signal	WARNING	'NoneType' object has no attribute 'stop'
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lisp/core/signal.py", line 71, in call
    self._reference()()
  File "/app/lib/python3.11/site-packages/lisp/cues/media_cue.py", line 233, in _on_error
    self.__fader.stop()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stop'
```

**Comment by FrancescoCeruti** [comment]
Apparently the runtime is no longer building GStreamer with jack support, for the moment is unusable from the flatpak.
