### ISSUE TITLE
Building LiSP 0.6 on Debian trixie

### ISSUE THREAD

**Issue by mitscherdinger** [FrancescoCeruti/linux-show-player#301]
**Describe the bug**
Following https://linux-show-player-users.readthedocs.io/en/latest/installation.html, it should lead to a functional LiSP. At least on debian testing (by the time writing this bugreport) I found 2 problems:

* liblo is not in the repository and can't be installed.
* "poetry install" is not able to install pycairo with this error message:

```
• Installing pycairo (1.25.1): Failed

  TypeError

  Can't instantiate abstract class IsolatedEnv with abstract methods executable, scripts_dir

  at /usr/lib/python3/dist-packages/poetry/installation/chef.py:131 in _prepare
      127│     ) -> Path:
      128│         from subprocess import CalledProcessError
      129│ 
      130│         with ephemeral_environment(self._env.python) as venv:
    → 131│             env = IsolatedEnv(venv, self._pool)
      132│             builder = ProjectBuilder.from_isolated_env(
      133│                 env, directory, runner=quiet_subprocess_runner
      134│             )
      135│             env.install(builder.build_system_requires)

Cannot install pycairo.
```
As a consequence, "poetry run linux-show-player" ends with…

 ```
poetry run linux-show-player
Warning: 'linux-show-player' is an entry point defined in pyproject.toml, but it's not installed as a script. You may get improper `sys.argv[0]`.

The support to run uninstalled scripts will be removed in a future release.

Run `poetry install` to resolve and get rid of this message.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mitsch/src/linux-show-player-0.6/lisp/__init__.py", line 20, in <module>
    from appdirs import AppDirs
ModuleNotFoundError: No module named 'appdirs'
```

**Linux Show Player version:**
0.6

**OS Version**
Debian Testing/Trixie

**Comment by FrancescoCeruti** [comment]
> liblo is not in the repository and can't be installed.

The package name is `liblo7`, I'll update the instructions :+1:

> "poetry install" is not able to install pycairo with this error message:

It seems a packaging problem, there's already an open ticket https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058670

You should uninstall the Debian version of `poetry` and try to install it "manually" (https://python-poetry.org/docs/#installation)

**Comment by mitscherdinger** [comment]
LiSP 0.6 runs! Thanks!
