### ISSUE TITLE
Network error on start up

### ISSUE THREAD

**Issue by j9p0** [FrancescoCeruti/linux-show-player#315]
**Describe the bug**
Every time I open up 0.6.* I get a network error. Also happens on new installs

**To Reproduce**
Just opening it

**Expected behavior**
No network error

**Screenshots**
![Screenshot from 2024-04-18 11-30-03](https://github.com/FrancescoCeruti/linux-show-player/assets/27363474/91e39131-6a74-4a17-a71b-1d9d32fa596d)

**Linux Show Player version:**
0.6.3 

**OS Version**
 on ubuntu 22.0.4.4 lts

**Additional context**
the details of the error. Seems that it can't bind to ip adress/port

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lisp/core/plugin_loader.py", line 106, in _load_plugin
    yield name, plugin(self.application)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lisp/plugins/network/network.py", line 40, in __init__
    self.server = APIServerThread(
                  ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lisp/plugins/network/server.py", line 30, in __init__
    self.wsgi_server = make_server(
                       ^^^^^^^^^^^^
  File "/usr/lib/python3.11/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lisp/core/plugin_loader.py", line 88, in _load_plugins
    yield from self._load_plugin(plugin, plugin_name)
  File "/app/lib/python3.11/site-packages/lisp/core/plugin_loader.py", line 114, in _load_plugin
    raise PluginInitFailedException(
lisp.core.plugin_loader.PluginInitFailedException: Failed to initialize plugin: "Network"

By the way, thanks for writing this great software! Been using 0.5 for some time now and it's great!

**Comment by s0600204** [comment]
Hi!

You're using the Flatpak, correct?

Do you happen to have the Open Lighting Architecture ([OLA](https://www.openlighting.org/ola/)) daemon `olad` running in the background?

**Comment by FrancescoCeruti** [comment]
This is usually because there's another instance of LiSP running or some other application is using the same network port used by `network` plugin.

Unless you need the plugin, you can disabled it in `File->Preferences->Plugins`
