### ISSUE TITLE
Fail to Initialize Plugin: Network at Fedora 40 KDE spin

### ISSUE THREAD

**Issue by luizimgiolo** [FrancescoCeruti/linux-show-player#324]
**Describe the bug**
At start show the error
Fail to Initialize Plugin: Network

**To Reproduce**
The error appears at the start of the software

Detailed as

  File "/app/lib/python3.11/site-packages/lisp/core/plugin_loader.py", line 106, in _load_plugin
    yield name, plugin(self.application)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lisp/plugins/network/network.py", line 40, in __init__
    self.server = APIServerThread(
                  ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lisp/plugins/network/server.py", line 30, in __init__
    self.wsgi_server = make_server(
                       ^^^^^^^^^^^^
  File "/usr/lib/python3.11/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Endereço já em uso

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lisp/core/plugin_loader.py", line 88, in _load_plugins
    yield from self._load_plugin(plugin, plugin_name)
  File "/app/lib/python3.11/site-packages/lisp/core/plugin_loader.py", line 114, in _load_plugin
    raise PluginInitFailedException(
lisp.core.plugin_loader.PluginInitFailedException: Failed to initialize plugin: "Network"

**OS Version**
 - Fedora 40 KDE

**Additional context**
Looks like that the software do not look for an alternative local port if the main one are already in use

**Comment by FrancescoCeruti** [comment]
Same as #315

I'll keep this open, since it looks like it's happening to a few people, we might implement a "fallback" port or some alternative method, like allowing users to pick their port.
