### ISSUE TITLE
Pressing global Stop Button 2 times throws error

### ISSUE THREAD

**Issue by offtools** [FrancescoCeruti/linux-show-player#42]
Hi,

just a small thing. Pressing the global Stop Button one time starts fade out of the running Cues. Hitting it the second time to stop the fade out also, throws an error:  

ERROR:: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lisp/core/signal.py", line 73, in call
    self._reference()(_args, *_kwargs)
  File "/usr/lib/python3.5/site-packages/lisp/layouts/list_layout/cue_list_model.py", line 130, in _remove
    self.__playing.remove(media)
ValueError: list.remove(x): x not in list

**Comment by offtools** [comment]
Thanks
