### ISSUE TITLE
Import error with 'pyqtWrapperType'

### ISSUE THREAD

**Issue by FelixINX** [FrancescoCeruti/linux-show-player#66]
On launch of the program, I get a Python traceback.
The error is about **pyqtWrapperType**.

I have installed the software using yaourt : `yaourt linux-show-player --noconfirm`. No error from this command.

#### Expected Behavior
````
$ linux-show-player
software loading...
````

#### Actual Behavior
````
$ linux-show-player

Traceback (most recent call last):
  File "/usr/bin/linux-show-player", line 3, in <module>
    from lisp.main import main
  File "/usr/lib/python3.6/site-packages/lisp/main.py", line 32, in <module>
    from lisp.application import Application
  File "/usr/lib/python3.6/site-packages/lisp/application.py", line 25, in <module>
    from lisp import layouts
  File "/usr/lib/python3.6/site-packages/lisp/layouts/__init__.py", line 1, in <module>
    from lisp.layouts.cart_layout.layout import CartLayout
  File "/usr/lib/python3.6/site-packages/lisp/layouts/cart_layout/layout.py", line 30, in <module>
    from lisp.layouts.cart_layout.cue_widget import CueWidget
  File "/usr/lib/python3.6/site-packages/lisp/layouts/cart_layout/cue_widget.py", line 28, in <module>
    from lisp.cues.cue_time import CueTime
  File "/usr/lib/python3.6/site-packages/lisp/cues/cue_time.py", line 24, in <module>
    from lisp.core.clock import Clock
  File "/usr/lib/python3.6/site-packages/lisp/core/clock.py", line 24, in <module>
    from lisp.core.singleton import QSingleton
  File "/usr/lib/python3.6/site-packages/lisp/core/singleton.py", line 22, in <module>
    from PyQt5.QtCore import pyqtWrapperType
ImportError: cannot import name 'pyqtWrapperType'
````
#### Step to reproduce
````
$ yaourt linux-show-player
$ linux-show-player
````

**Comment by FelixINX** [comment]
Fixed with the git version.
