### ISSUE TITLE
Backend loading

### ISSUE THREAD

**Issue by ulneij** [FrancescoCeruti/linux-show-player#85]
Hello!

I hope this is the right place for asking help, I couldn't find the answer I need on the net.

After making the package executable, v0.5 64 bits, I have this error at openning : 
#Backend loading failed: mido.backends.rtmidi

and at adding a audio cue (Ctrl+M):
#Backend not loaded

I don't need the midi to be working for now, but how to make audio cues working?
I reckon it has to do with GStreamer. Synaptic Package Manager says it's installed, but maybe not the right one? I am using PulseAudio for sound, and it's a LinuxMint 17.3.

Thank you!

Julien

**Comment by FrancescoCeruti** [comment]
Hi,
the appimage it's mostly independent form the system packages, so your GStreamer installation should not be a problem, can you run it from the command line with `-l debug` and post the output here?

**Comment by ulneij** [comment]
Thank you for answering!
Here it is : 

julien@julien-Precision-M6400 ~/LiSP $ ./LiSP.AppImage -l debug
21:55:45.941 INFO:: Using en_GB locale
21:55:46.394 DEBUG:: ACTION-CUES: Loaded "CollectionCue"
21:55:46.395 DEBUG:: ACTION-CUES: Loaded "CommandCue"
21:55:46.397 DEBUG:: ACTION-CUES: Loaded "IndexActionCue"
21:55:46.429 DEBUG:: ACTION-CUES: Loaded "MidiCue"
21:55:46.431 DEBUG:: ACTION-CUES: Loaded "SeekCue"
21:55:46.431 DEBUG:: ACTION-CUES: Loaded "StopAll"
21:55:46.434 DEBUG:: ACTION-CUES: Loaded "VolumeControl"
21:55:46.434 DEBUG:: MODULES: Loaded "ActionCues"
21:55:46.629 WARNING:: Cannot load module: gst_backend
21:55:46.638 DEBUG:: Traceback (most recent call last):
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/__init__.py", line 4, in <module>
    from .gst_backend import GstBackend
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/gst_backend.py", line 25, in <module>
    from lisp.modules.gst_backend.gst_utils import gst_parse_tag_list
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/gst_utils.py", line 23, in <module>
    from lisp.modules.gst_backend.gi_repository import Gst, GstPbutils
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/gi_repository.py", line 9, in <module>
    import gi
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so: undefined symbol: g_type_check_instance_is_fundamentally_a

21:55:46.641 DEBUG:: MODULES: Loaded "MediaCueMenus"
21:55:46.819 WARNING:: Cannot load module: media_info
21:55:46.821 DEBUG:: Traceback (most recent call last):
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/media_info/__init__.py", line 1, in <module>
    from .media_info import MediaInfo
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/media_info/media_info.py", line 28, in <module>
    from lisp.modules.gst_backend.gst_utils import gst_uri_metadata, \
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/__init__.py", line 4, in <module>
    from .gst_backend import GstBackend
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/gst_backend.py", line 25, in <module>
    from lisp.modules.gst_backend.gst_utils import gst_parse_tag_list
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/gst_utils.py", line 23, in <module>
    from lisp.modules.gst_backend.gi_repository import Gst, GstPbutils
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/gst_backend/gi_repository.py", line 9, in <module>
    import gi
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so: undefined symbol: g_type_check_instance_is_fundamentally_a

21:55:46.890 ERROR:: Failed "Midi" lading
Details: Traceback (most recent call last):
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/singleton.py", line 41, in __call__
    return cls.__instance
AttributeError: type object 'Midi' has no attribute '_ABCSingleton__instance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/midi/midi.py", line 38, in __init__
    mido.set_backend(mido.Backend(bk_name, load=True))
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/mido/backends/backend.py", line 31, in __init__
    self.load()
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/mido/backends/backend.py", line 57, in load
    self._module = importlib.import_module(self.name)
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/mido/backends/rtmidi.py", line 17, in <module>
    import rtmidi
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/rtmidi/__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/rtmidi/_rtmidi.cpython-35m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/__init__.py", line 31, in load_modules
    __MODULES[name] = module()
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/singleton.py", line 43, in __call__
    cls.__instance = super(ABCSingleton, cls).__call__(*args, **kwargs)
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/midi/midi.py", line 40, in __init__
    raise RuntimeError('Backend loading failed: {0}'.format(bk_name))
RuntimeError: Backend loading failed: mido.backends.rtmidi

21:55:54.589 DEBUG:: MODULES: Loaded "Presets"
21:55:54.794 INFO:: REMOTE: Session started at ('0.0.0.0', 8070)
21:55:54.794 DEBUG:: MODULES: Loaded "Remote"
21:55:54.882 WARNING:: Cannot load module: replay_gain
21:55:54.885 DEBUG:: Traceback (most recent call last):
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/replay_gain/__init__.py", line 1, in <module>
    from .replay_gain import ReplayGain
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/lisp/modules/replay_gain/replay_gain.py", line 26, in <module>
    import gi
  File "/tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /tmp/.mount_UhjKxZ/usr/lib/python3.5/site-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so: undefined symbol: g_type_check_instance_is_fundamentally_a

21:55:54.888 DEBUG:: MODULES: Loaded "UriChanger"
21:55:54.896 DEBUG:: PLUGINS: Loaded "Controller"
21:55:54.898 DEBUG:: PLUGINS: Loaded "Synchronizer"
21:55:55.304 DEBUG:: PLUGINS: Loaded "Timecode"
21:55:55.306 DEBUG:: PLUGINS: Loaded "Triggers"
21:56:09.103 DEBUG:: PLUGINS: Initialized "Synchronizer"
21:56:09.103 DEBUG:: PLUGINS: Initialized "Triggers"
21:56:09.103 DEBUG:: PLUGINS: Initialized "Controller"
21:56:09.103 INFO:: TIMECODE: disabled, OLA not running
21:56:09.103 DEBUG:: PLUGINS: Initialized "Timecode"
QXcbConnection: XCB error: 3 (BadWindow), sequence: 962, resource id: 8406097, major code: 40 (TranslateCoords), minor code: 0
21:57:14.903 DEBUG:: MODULES: Terminated "Remote"
21:57:14.903 DEBUG:: MODULES: Terminated "Presets"
21:57:14.903 DEBUG:: MODULES: Terminated "MediaCueMenus"
21:57:14.903 DEBUG:: MODULES: Terminated "UriChanger"
21:57:14.903 DEBUG:: MODULES: Terminated "ActionCues"
21:57:14.904 DEBUG:: PLUGINS: Reset "Synchronizer"
21:57:14.904 DEBUG:: PLUGINS: Reset "Triggers"
21:57:14.904 DEBUG:: PLUGINS: Reset "Controller"
21:57:14.904 DEBUG:: PLUGINS: Reset "Timecode"
21:57:14.904 INFO:: REMOTE: Session ended
Segmentation fault
julien@julien-Precision-M6400 ~/LiSP $

**Comment by FrancescoCeruti** [comment]
I've checked and Mint 17.3 is based on Ubuntu 14.04 which is not supported by the AppImage (Ubuntu 16.04 and later), you should upgrade to Mint 18, or try a manual installation if you cannot upgrade, you can find [here](https://github.com/FrancescoCeruti/linux-show-player/wiki/Install) what you need.

**Comment by ulneij** [comment]
Francesco, I just installed Mint 18 and it works perfectly! Thank you again, both for helping me and for releasing such a great program!
